/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as RestaurantRouteImport } from './routes/restaurant'
import { Route as ReserverRouteImport } from './routes/reserver'
import { Route as OffresRouteImport } from './routes/offres'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as GalerieRouteImport } from './routes/galerie'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ExperiencesRouteImport } from './routes/experiences'
import { Route as EvenementsRouteImport } from './routes/evenements'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as ComparerRouteImport } from './routes/comparer'
import { Route as ChambresRouteImport } from './routes/chambres'
import { Route as CgvRouteImport } from './routes/cgv'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChambresIdRouteImport } from './routes/chambres.$id'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthenticatedMesReservationsRouteImport } from './routes/_authenticated/mes-reservations'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminUtilisateursRouteImport } from './routes/_authenticated/admin/utilisateurs'
import { Route as AuthenticatedAdminStockRouteImport } from './routes/_authenticated/admin/stock'
import { Route as AuthenticatedAdminRestaurantRouteImport } from './routes/_authenticated/admin/restaurant'
import { Route as AuthenticatedAdminReservationsRouteImport } from './routes/_authenticated/admin/reservations'
import { Route as AuthenticatedAdminRapportsRouteImport } from './routes/_authenticated/admin/rapports'
import { Route as AuthenticatedAdminPlanningRouteImport } from './routes/_authenticated/admin/planning'
import { Route as AuthenticatedAdminMessagesRouteImport } from './routes/_authenticated/admin/messages'
import { Route as AuthenticatedAdminFinanceRouteImport } from './routes/_authenticated/admin/finance'
import { Route as AuthenticatedAdminClientsRouteImport } from './routes/_authenticated/admin/clients'
import { Route as AuthenticatedAdminChambresRouteImport } from './routes/_authenticated/admin/chambres'
import { Route as AuthenticatedAdminClientsIdRouteImport } from './routes/_authenticated/admin/clients.$id'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantRoute = RestaurantRouteImport.update({
  id: '/restaurant',
  path: '/restaurant',
  getParentRoute: () => rootRouteImport,
} as any)
const ReserverRoute = ReserverRouteImport.update({
  id: '/reserver',
  path: '/reserver',
  getParentRoute: () => rootRouteImport,
} as any)
const OffresRoute = OffresRouteImport.update({
  id: '/offres',
  path: '/offres',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const GalerieRoute = GalerieRouteImport.update({
  id: '/galerie',
  path: '/galerie',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesRoute = ExperiencesRouteImport.update({
  id: '/experiences',
  path: '/experiences',
  getParentRoute: () => rootRouteImport,
} as any)
const EvenementsRoute = EvenementsRouteImport.update({
  id: '/evenements',
  path: '/evenements',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparerRoute = ComparerRouteImport.update({
  id: '/comparer',
  path: '/comparer',
  getParentRoute: () => rootRouteImport,
} as any)
const ChambresRoute = ChambresRouteImport.update({
  id: '/chambres',
  path: '/chambres',
  getParentRoute: () => rootRouteImport,
} as any)
const CgvRoute = CgvRouteImport.update({
  id: '/cgv',
  path: '/cgv',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChambresIdRoute = ChambresIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ChambresRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AuthenticatedMesReservationsRoute =
  AuthenticatedMesReservationsRouteImport.update({
    id: '/mes-reservations',
    path: '/mes-reservations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminUtilisateursRoute =
  AuthenticatedAdminUtilisateursRouteImport.update({
    id: '/utilisateurs',
    path: '/utilisateurs',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminStockRoute = AuthenticatedAdminStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminRestaurantRoute =
  AuthenticatedAdminRestaurantRouteImport.update({
    id: '/restaurant',
    path: '/restaurant',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminReservationsRoute =
  AuthenticatedAdminReservationsRouteImport.update({
    id: '/reservations',
    path: '/reservations',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminRapportsRoute =
  AuthenticatedAdminRapportsRouteImport.update({
    id: '/rapports',
    path: '/rapports',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPlanningRoute =
  AuthenticatedAdminPlanningRouteImport.update({
    id: '/planning',
    path: '/planning',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminMessagesRoute =
  AuthenticatedAdminMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminFinanceRoute =
  AuthenticatedAdminFinanceRouteImport.update({
    id: '/finance',
    path: '/finance',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminClientsRoute =
  AuthenticatedAdminClientsRouteImport.update({
    id: '/clients',
    path: '/clients',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminChambresRoute =
  AuthenticatedAdminChambresRouteImport.update({
    id: '/chambres',
    path: '/chambres',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminClientsIdRoute =
  AuthenticatedAdminClientsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminClientsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/cgv': typeof CgvRoute
  '/chambres': typeof ChambresRouteWithChildren
  '/comparer': typeof ComparerRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/evenements': typeof EvenementsRoute
  '/experiences': typeof ExperiencesRoute
  '/faq': typeof FaqRoute
  '/galerie': typeof GalerieRoute
  '/guide': typeof GuideRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/offres': typeof OffresRoute
  '/reserver': typeof ReserverRoute
  '/restaurant': typeof RestaurantRoute
  '/services': typeof ServicesRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/mes-reservations': typeof AuthenticatedMesReservationsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/chambres/$id': typeof ChambresIdRoute
  '/admin/chambres': typeof AuthenticatedAdminChambresRoute
  '/admin/clients': typeof AuthenticatedAdminClientsRouteWithChildren
  '/admin/finance': typeof AuthenticatedAdminFinanceRoute
  '/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/admin/planning': typeof AuthenticatedAdminPlanningRoute
  '/admin/rapports': typeof AuthenticatedAdminRapportsRoute
  '/admin/reservations': typeof AuthenticatedAdminReservationsRoute
  '/admin/restaurant': typeof AuthenticatedAdminRestaurantRoute
  '/admin/stock': typeof AuthenticatedAdminStockRoute
  '/admin/utilisateurs': typeof AuthenticatedAdminUtilisateursRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/clients/$id': typeof AuthenticatedAdminClientsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/cgv': typeof CgvRoute
  '/chambres': typeof ChambresRouteWithChildren
  '/comparer': typeof ComparerRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/evenements': typeof EvenementsRoute
  '/experiences': typeof ExperiencesRoute
  '/faq': typeof FaqRoute
  '/galerie': typeof GalerieRoute
  '/guide': typeof GuideRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/offres': typeof OffresRoute
  '/reserver': typeof ReserverRoute
  '/restaurant': typeof RestaurantRoute
  '/services': typeof ServicesRoute
  '/mes-reservations': typeof AuthenticatedMesReservationsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/chambres/$id': typeof ChambresIdRoute
  '/admin/chambres': typeof AuthenticatedAdminChambresRoute
  '/admin/clients': typeof AuthenticatedAdminClientsRouteWithChildren
  '/admin/finance': typeof AuthenticatedAdminFinanceRoute
  '/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/admin/planning': typeof AuthenticatedAdminPlanningRoute
  '/admin/rapports': typeof AuthenticatedAdminRapportsRoute
  '/admin/reservations': typeof AuthenticatedAdminReservationsRoute
  '/admin/restaurant': typeof AuthenticatedAdminRestaurantRoute
  '/admin/stock': typeof AuthenticatedAdminStockRoute
  '/admin/utilisateurs': typeof AuthenticatedAdminUtilisateursRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/clients/$id': typeof AuthenticatedAdminClientsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/a-propos': typeof AProposRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/cgv': typeof CgvRoute
  '/chambres': typeof ChambresRouteWithChildren
  '/comparer': typeof ComparerRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/evenements': typeof EvenementsRoute
  '/experiences': typeof ExperiencesRoute
  '/faq': typeof FaqRoute
  '/galerie': typeof GalerieRoute
  '/guide': typeof GuideRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/offres': typeof OffresRoute
  '/reserver': typeof ReserverRoute
  '/restaurant': typeof RestaurantRoute
  '/services': typeof ServicesRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/mes-reservations': typeof AuthenticatedMesReservationsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/chambres/$id': typeof ChambresIdRoute
  '/_authenticated/admin/chambres': typeof AuthenticatedAdminChambresRoute
  '/_authenticated/admin/clients': typeof AuthenticatedAdminClientsRouteWithChildren
  '/_authenticated/admin/finance': typeof AuthenticatedAdminFinanceRoute
  '/_authenticated/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/_authenticated/admin/planning': typeof AuthenticatedAdminPlanningRoute
  '/_authenticated/admin/rapports': typeof AuthenticatedAdminRapportsRoute
  '/_authenticated/admin/reservations': typeof AuthenticatedAdminReservationsRoute
  '/_authenticated/admin/restaurant': typeof AuthenticatedAdminRestaurantRoute
  '/_authenticated/admin/stock': typeof AuthenticatedAdminStockRoute
  '/_authenticated/admin/utilisateurs': typeof AuthenticatedAdminUtilisateursRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/clients/$id': typeof AuthenticatedAdminClientsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/auth'
    | '/blog'
    | '/cgv'
    | '/chambres'
    | '/comparer'
    | '/confidentialite'
    | '/contact'
    | '/evenements'
    | '/experiences'
    | '/faq'
    | '/galerie'
    | '/guide'
    | '/mentions-legales'
    | '/offres'
    | '/reserver'
    | '/restaurant'
    | '/services'
    | '/admin'
    | '/mes-reservations'
    | '/blog/$slug'
    | '/chambres/$id'
    | '/admin/chambres'
    | '/admin/clients'
    | '/admin/finance'
    | '/admin/messages'
    | '/admin/planning'
    | '/admin/rapports'
    | '/admin/reservations'
    | '/admin/restaurant'
    | '/admin/stock'
    | '/admin/utilisateurs'
    | '/admin/'
    | '/admin/clients/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/auth'
    | '/blog'
    | '/cgv'
    | '/chambres'
    | '/comparer'
    | '/confidentialite'
    | '/contact'
    | '/evenements'
    | '/experiences'
    | '/faq'
    | '/galerie'
    | '/guide'
    | '/mentions-legales'
    | '/offres'
    | '/reserver'
    | '/restaurant'
    | '/services'
    | '/mes-reservations'
    | '/blog/$slug'
    | '/chambres/$id'
    | '/admin/chambres'
    | '/admin/clients'
    | '/admin/finance'
    | '/admin/messages'
    | '/admin/planning'
    | '/admin/rapports'
    | '/admin/reservations'
    | '/admin/restaurant'
    | '/admin/stock'
    | '/admin/utilisateurs'
    | '/admin'
    | '/admin/clients/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/a-propos'
    | '/auth'
    | '/blog'
    | '/cgv'
    | '/chambres'
    | '/comparer'
    | '/confidentialite'
    | '/contact'
    | '/evenements'
    | '/experiences'
    | '/faq'
    | '/galerie'
    | '/guide'
    | '/mentions-legales'
    | '/offres'
    | '/reserver'
    | '/restaurant'
    | '/services'
    | '/_authenticated/admin'
    | '/_authenticated/mes-reservations'
    | '/blog/$slug'
    | '/chambres/$id'
    | '/_authenticated/admin/chambres'
    | '/_authenticated/admin/clients'
    | '/_authenticated/admin/finance'
    | '/_authenticated/admin/messages'
    | '/_authenticated/admin/planning'
    | '/_authenticated/admin/rapports'
    | '/_authenticated/admin/reservations'
    | '/_authenticated/admin/restaurant'
    | '/_authenticated/admin/stock'
    | '/_authenticated/admin/utilisateurs'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/clients/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AProposRoute: typeof AProposRoute
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRouteWithChildren
  CgvRoute: typeof CgvRoute
  ChambresRoute: typeof ChambresRouteWithChildren
  ComparerRoute: typeof ComparerRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  ContactRoute: typeof ContactRoute
  EvenementsRoute: typeof EvenementsRoute
  ExperiencesRoute: typeof ExperiencesRoute
  FaqRoute: typeof FaqRoute
  GalerieRoute: typeof GalerieRoute
  GuideRoute: typeof GuideRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  OffresRoute: typeof OffresRoute
  ReserverRoute: typeof ReserverRoute
  RestaurantRoute: typeof RestaurantRoute
  ServicesRoute: typeof ServicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant': {
      id: '/restaurant'
      path: '/restaurant'
      fullPath: '/restaurant'
      preLoaderRoute: typeof RestaurantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reserver': {
      id: '/reserver'
      path: '/reserver'
      fullPath: '/reserver'
      preLoaderRoute: typeof ReserverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offres': {
      id: '/offres'
      path: '/offres'
      fullPath: '/offres'
      preLoaderRoute: typeof OffresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galerie': {
      id: '/galerie'
      path: '/galerie'
      fullPath: '/galerie'
      preLoaderRoute: typeof GalerieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences': {
      id: '/experiences'
      path: '/experiences'
      fullPath: '/experiences'
      preLoaderRoute: typeof ExperiencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evenements': {
      id: '/evenements'
      path: '/evenements'
      fullPath: '/evenements'
      preLoaderRoute: typeof EvenementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparer': {
      id: '/comparer'
      path: '/comparer'
      fullPath: '/comparer'
      preLoaderRoute: typeof ComparerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chambres': {
      id: '/chambres'
      path: '/chambres'
      fullPath: '/chambres'
      preLoaderRoute: typeof ChambresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgv': {
      id: '/cgv'
      path: '/cgv'
      fullPath: '/cgv'
      preLoaderRoute: typeof CgvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chambres/$id': {
      id: '/chambres/$id'
      path: '/$id'
      fullPath: '/chambres/$id'
      preLoaderRoute: typeof ChambresIdRouteImport
      parentRoute: typeof ChambresRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/_authenticated/mes-reservations': {
      id: '/_authenticated/mes-reservations'
      path: '/mes-reservations'
      fullPath: '/mes-reservations'
      preLoaderRoute: typeof AuthenticatedMesReservationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/utilisateurs': {
      id: '/_authenticated/admin/utilisateurs'
      path: '/utilisateurs'
      fullPath: '/admin/utilisateurs'
      preLoaderRoute: typeof AuthenticatedAdminUtilisateursRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/stock': {
      id: '/_authenticated/admin/stock'
      path: '/stock'
      fullPath: '/admin/stock'
      preLoaderRoute: typeof AuthenticatedAdminStockRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/restaurant': {
      id: '/_authenticated/admin/restaurant'
      path: '/restaurant'
      fullPath: '/admin/restaurant'
      preLoaderRoute: typeof AuthenticatedAdminRestaurantRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/reservations': {
      id: '/_authenticated/admin/reservations'
      path: '/reservations'
      fullPath: '/admin/reservations'
      preLoaderRoute: typeof AuthenticatedAdminReservationsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/rapports': {
      id: '/_authenticated/admin/rapports'
      path: '/rapports'
      fullPath: '/admin/rapports'
      preLoaderRoute: typeof AuthenticatedAdminRapportsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/planning': {
      id: '/_authenticated/admin/planning'
      path: '/planning'
      fullPath: '/admin/planning'
      preLoaderRoute: typeof AuthenticatedAdminPlanningRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/messages': {
      id: '/_authenticated/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AuthenticatedAdminMessagesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/finance': {
      id: '/_authenticated/admin/finance'
      path: '/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AuthenticatedAdminFinanceRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/clients': {
      id: '/_authenticated/admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AuthenticatedAdminClientsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/chambres': {
      id: '/_authenticated/admin/chambres'
      path: '/chambres'
      fullPath: '/admin/chambres'
      preLoaderRoute: typeof AuthenticatedAdminChambresRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/clients/$id': {
      id: '/_authenticated/admin/clients/$id'
      path: '/$id'
      fullPath: '/admin/clients/$id'
      preLoaderRoute: typeof AuthenticatedAdminClientsIdRouteImport
      parentRoute: typeof AuthenticatedAdminClientsRoute
    }
  }
}

interface AuthenticatedAdminClientsRouteChildren {
  AuthenticatedAdminClientsIdRoute: typeof AuthenticatedAdminClientsIdRoute
}

const AuthenticatedAdminClientsRouteChildren: AuthenticatedAdminClientsRouteChildren =
  {
    AuthenticatedAdminClientsIdRoute: AuthenticatedAdminClientsIdRoute,
  }

const AuthenticatedAdminClientsRouteWithChildren =
  AuthenticatedAdminClientsRoute._addFileChildren(
    AuthenticatedAdminClientsRouteChildren,
  )

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminChambresRoute: typeof AuthenticatedAdminChambresRoute
  AuthenticatedAdminClientsRoute: typeof AuthenticatedAdminClientsRouteWithChildren
  AuthenticatedAdminFinanceRoute: typeof AuthenticatedAdminFinanceRoute
  AuthenticatedAdminMessagesRoute: typeof AuthenticatedAdminMessagesRoute
  AuthenticatedAdminPlanningRoute: typeof AuthenticatedAdminPlanningRoute
  AuthenticatedAdminRapportsRoute: typeof AuthenticatedAdminRapportsRoute
  AuthenticatedAdminReservationsRoute: typeof AuthenticatedAdminReservationsRoute
  AuthenticatedAdminRestaurantRoute: typeof AuthenticatedAdminRestaurantRoute
  AuthenticatedAdminStockRoute: typeof AuthenticatedAdminStockRoute
  AuthenticatedAdminUtilisateursRoute: typeof AuthenticatedAdminUtilisateursRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminChambresRoute: AuthenticatedAdminChambresRoute,
    AuthenticatedAdminClientsRoute: AuthenticatedAdminClientsRouteWithChildren,
    AuthenticatedAdminFinanceRoute: AuthenticatedAdminFinanceRoute,
    AuthenticatedAdminMessagesRoute: AuthenticatedAdminMessagesRoute,
    AuthenticatedAdminPlanningRoute: AuthenticatedAdminPlanningRoute,
    AuthenticatedAdminRapportsRoute: AuthenticatedAdminRapportsRoute,
    AuthenticatedAdminReservationsRoute: AuthenticatedAdminReservationsRoute,
    AuthenticatedAdminRestaurantRoute: AuthenticatedAdminRestaurantRoute,
    AuthenticatedAdminStockRoute: AuthenticatedAdminStockRoute,
    AuthenticatedAdminUtilisateursRoute: AuthenticatedAdminUtilisateursRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedMesReservationsRoute: typeof AuthenticatedMesReservationsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedMesReservationsRoute: AuthenticatedMesReservationsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface ChambresRouteChildren {
  ChambresIdRoute: typeof ChambresIdRoute
}

const ChambresRouteChildren: ChambresRouteChildren = {
  ChambresIdRoute: ChambresIdRoute,
}

const ChambresRouteWithChildren = ChambresRoute._addFileChildren(
  ChambresRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AProposRoute: AProposRoute,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRouteWithChildren,
  CgvRoute: CgvRoute,
  ChambresRoute: ChambresRouteWithChildren,
  ComparerRoute: ComparerRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  ContactRoute: ContactRoute,
  EvenementsRoute: EvenementsRoute,
  ExperiencesRoute: ExperiencesRoute,
  FaqRoute: FaqRoute,
  GalerieRoute: GalerieRoute,
  GuideRoute: GuideRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  OffresRoute: OffresRoute,
  ReserverRoute: ReserverRoute,
  RestaurantRoute: RestaurantRoute,
  ServicesRoute: ServicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
